# Colors
BACKGROUND = "#f5f5f5"
PRIMARY = "#2563eb"
DANGER = "#dc2626"
TEXT = "#111827"
MUTED = "#6b7280"

# Fonts
FONT_FAMILY = "Helvetica"
FONT_TITLE = (FONT_FAMILY, 20, "bold")
FONT_HEADER = (FONT_FAMILY, 16, "bold")
FONT_SECTION = (FONT_FAMILY, 11, "bold")
FONT_LABEL = (FONT_FAMILY, 12)
FONT_BODY = (FONT_FAMILY, 11)
